import { Rubik } from "next/font/google";
import "./globals.css";


const rubik = Rubik({
    // variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata = {
  title: "Dojo Helpdesk",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={rubik.className}>
        {children}
      </body>
    </html>
  );
}
